# Generated by Django 3.1.5 on 2021-01-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.AddField(
            model_name='member',
            name='absent',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='attendance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='etc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='major',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='tardy',
            field=models.IntegerField(null=True),
        ),
    ]
