# Generated by Django 3.1.5 on 2021-01-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210127_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='absent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='attendance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='etc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='tardy',
            field=models.IntegerField(default=0),
        ),
    ]
